"""Generate a native-language Russia feed for every country.

55 of 99 registry countries have no source in their own language — we see them
only through English/Russian media. This fills that gap with the worldmonitor
universal adapter: each country's own Google News edition, queried about Russia
in the native language (src/collectors/gnews.native_feed_url). Probed live, each
returns ~100 fresh native-language Russia items.

Output is a generated, regenerable catalog merged by config.load_sources():
    src/collectors/sources_native.yaml
Every feed is validated (HTTP 200 / valid RSS / has items) before inclusion —
a country whose edition doesn't validate is skipped and logged, never shipped.

Usage:
    python scripts/add_native_feeds.py --dry-run    # probe + report only
    python scripts/add_native_feeds.py              # write sources_native.yaml
"""
import argparse
import logging

from src.collectors.gnews import RUSSIA_TERM, native_feed_url
from src.config import NATIVE_SOURCES_PATH
from src.countries import COUNTRIES, country_name_ru
from scripts.validate_feed import validate_url

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
logger = logging.getLogger("add-native-feeds")

MIN_ITEMS = 5  # a real edition returns dozens; this rejects empty/broken ones

HEADER = (
    "# GENERATED by scripts/add_native_feeds.py — do not edit by hand.\n"
    "# Native-language Google News \"Russia\" feed per country (fills the\n"
    "# native-language coverage gap). Regenerate to refresh. Merged by\n"
    "# config.load_sources() after sources.yaml + sources_world.yaml.\n"
)


def build() -> dict[str, dict]:
    """Probe each non-English-primary country; return {cc: {lang, url, items}}."""
    out = {}
    targets = [(cc, c["langs"][0]) for cc, c in COUNTRIES.items()
               if c["langs"] and c["langs"][0] != "en"]
    logger.info("Probing native editions for %d countries...", len(targets))
    for cc, lang in sorted(targets):
        url = native_feed_url(cc, lang)
        res = validate_url(url, "rss")
        if res["ok"] and res["n_items"] >= MIN_ITEMS:
            out[cc] = {"lang": lang, "url": url, "items": res["n_items"]}
            logger.info("OK   %s/%s  %3d items%s", cc, lang, res["n_items"],
                        "" if lang in RUSSIA_TERM else "  (term fallback=Russia)")
        else:
            logger.warning("SKIP %s/%s  %s", cc, lang, res["reason"][:60])
    return out


def render_yaml(data: dict[str, dict]) -> str:
    lines = [HEADER, "countries:"]
    for cc in sorted(data):
        d = data[cc]
        lines.append(f"  {cc}:")
        lines.append(f"    name: {country_name_ru(cc)}")
        lines.append(f"    sources:")
        lines.append(f'      - name: "Google News ({d["lang"].upper()}) — Россия"')
        lines.append(f"        type: rss")
        lines.append(f'        url: "{d["url"]}"')
        lines.append(f"        weight: 1.0")
        lines.append(f"        language: {d['lang']}")
        lines.append(f"        tier: mainstream")
        lines.append(f"        state_affiliated: false")
        lines.append(f"        propaganda_risk: low")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description="Generate native-language Russia feeds")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    data = build()
    logger.info("=== %d native feeds validated ===", len(data))
    if args.dry_run:
        logger.info("dry-run: %s not written", NATIVE_SOURCES_PATH.name)
        return
    NATIVE_SOURCES_PATH.write_text(render_yaml(data))
    logger.info("Wrote %d countries to %s", len(data), NATIVE_SOURCES_PATH)


if __name__ == "__main__":
    main()
